[project]
name = "projet-kmeans"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cmake>=4.3.2",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.9",
    "numpy>=2.4.5",
    "pandas>=3.0.3",
    "pybind11>=3.0.4",
    "scikit-learn>=1.8.0",
]
